### PR TITLE
An implementation of show for MathOptNLPModel and MathOptNLSModel

### PR DESCRIPTION
**Pull request by amontoison**
@abelsiqueira

### CODE REVIEW

**Comment by amontoison** [comment]
```
Testing show on MathOptNLPModel
brownden MathOptNLPModel
The objective function is NONLINEAR.
The model has 4 variables and 0 constraint.

hs5 MathOptNLPModel
The objective function is NONLINEAR.
The model has 2 variables and 0 constraint.

hs6 MathOptNLPModel
The objective function is NONLINEAR.
The model has 2 variables and 1 constraint.

hs10 MathOptNLPModel
The objective function is LINEAR.
The model has 2 variables and 1 constraint.

hs11 MathOptNLPModel
The objective function is QUADRATIC.
The model has 2 variables and 1 constraint.

hs14 MathOptNLPModel
The objective function is QUADRATIC.
The model has 2 variables and 2 constraints.

lincon MathOptNLPModel
The objective function is NONLINEAR.
The model has 15 variables and 11 constraints.

linsv MathOptNLPModel
The objective function is LINEAR.
The model has 2 variables and 2 constraints.
```

```
Testing show on MathOptNLSModel
mgh01 MathOptNLSModel
The model has 2 variables, 2 equations and 0 constraint.

mgh07 MathOptNLSModel
The model has 3 variables, 3 equations and 0 constraint.

lls MathOptNLSModel
The model has 2 variables, 3 equations and 1 constraint.

hs30 MathOptNLSModel
The model has 3 variables, 3 equations and 1 constraint.

hs43 MathOptNLSModel
The model has 4 variables, 4 equations and 3 constraints.

nlshs20 MathOptNLSModel
The model has 2 variables, 2 equations and 3 constraints.

nlslc MathOptNLSModel
The model has 15 variables, 15 equations and 11 constraints.
```

**Comment by dpo** [comment]
This could probably go directly into NLPModels.jl?!

JuMP models have a sophisticated `show` method, which displays the LaTeX (at least in Jupyter). Maybe MathOptNL[PS]Models could show that in addition to the basic `show`?

We should also display more info, including:
* number of bounds;
* number of linear (in)equality constraints;
* number of nonlinear (in)equality constraints;
* nature of the objective (linear, nonlinear, ... quadratic?);
* nnzj, nnzh;
* etc.

For NLS models, is there a way to distinguish between linear and nonlinear residuals?

**Comment by abelsiqueira** [comment]
I was working on one implementation for NLPModels.jl, but it is still missing some models: https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/287

**Comment by abelsiqueira** [comment]
Maybe the `show` function could focus on the basics, and we can create a `describe` function with more information?

**Comment by amontoison** [comment]
@dpo, the JuMP model is not stored inside the MathOptNL[PS]Models. I can't use their `show`.

For NLS models, we could distinguish (linear + quadratic)  and other nonlinear residuals. We just need to use `@expression` instead of `@NLexpression`. But it seems that no on  is working on NLS models recently, so I don't improved it for the time being.

PS : I wanted to add an example on a model of `NLSProblems` last month and I'm still waiting a new release. :worried: 
https://github.com/JuliaSmoothOptimizers/NLSProblems.jl/issues/42

**Comment by abelsiqueira** [comment]
NLPModelsJuMP 0.6.3 was release a couple days ago.

**Comment by dpo** [comment]
> Maybe the show function could focus on the basics, and we can create a describe function with more information?

One `show` can call another. It would be easy enough to store the JuMP model.

**Comment by dpo** [comment]
> I'm still waiting a new release. 😟

you only need to submit a PR that bumps the version number :-)

**Comment by amontoison** [comment]
Already done the 8 march when I did the transition between `MathProgNLSModel` and `MathOptNLSModel` : https://github.com/JuliaSmoothOptimizers/NLSProblems.jl/pull/37 :wink: 
But I should do a specific commit when I bump the version number.

**Comment by dpo** [comment]
There's the risk of not keeping pull requests focused.

**Pull request closed without merging**
