### PR TITLE
Test view subarray and add precompile

### PR DESCRIPTION
**Pull request by abelsiqueira**
Related to JuliaSmoothOptimizers/NLPModelsJuMP.jl#7.
Needs mlubin/ReverseDiffSparse.jl#54 and https://github.com/JuliaOpt/JuMP.jl/pull/1548

### CODE REVIEW

**Comment by dpo** [comment]
There we go.

**Comment by dpo** [comment]
```
Expression: foo(nlp, x[I]) == foo(nlp, #= /home/travis/build/JuliaSmoothOptimizers/NLPModelsJuMP.jl/test/test_view_subarray.jl:14 =# @view(x[I]))
MethodError: no method matching eval_hesslag(::JuMP.NLPEvaluator, ::Array{Float64,1}, ::SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true}, ::Float64, ::Array{Float64,1})
```
https://travis-ci.org/JuliaSmoothOptimizers/NLPModelsJuMP.jl/jobs/441172017#L797

**Comment by abelsiqueira** [comment]
This is also gonna need a new JuMP 0.18 release.

**Comment by dpo** [comment]
Any progress on this?

**Comment by abelsiqueira** [comment]
I'll ask for a new JuMP 0.18 release so we can test.

**Comment by abelsiqueira** [comment]
Rebased and updated requirement to JuMP 0.18.5.

**Comment by dpo** [comment]
Excellent! Thank you!

**Pull request merged**
