### PR TITLE
Update 1.0

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
I thought there was no MPB beyond Julia 0.6?!

**Comment by abelsiqueira** [comment]
Very fresh: https://github.com/JuliaOpt/JuMP.jl/pull/1511

**Comment by dpo** [comment]
I guess I don't understand the connexion between MPB and MOI.

**Comment by abelsiqueira** [comment]
As far as I understand, and @mlubin can correct me:
- About a year ago they realized MPB needed to be rewri, naming it MOI;
- A few months ago, with the Julia 1.0 release, most core developers decided to invest on finishing MOI and releasing JuMP with MOI (JuMP 0.19) instead of updating MPB (and JuMP with MPB) to 1.0;
- Mostly due to @expandingman, JuMP and MPB were updated to Julia 1.0;
- JuMP 0.18.x will be the last one to use MPB, and JuMP 0.18.3 is the first to support Julia 1.0.

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
