### PR TITLE
Fix tests on Julia nightly

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by tmigot** [comment]
Any idea of what is still breaking here?

**Comment by amontoison** [comment]
It works with `Julia 1.8-rc3`. I will compile the nightly version to solve the issue.

**Comment by amontoison** [comment]
The issue is with `JuMP.Containers.SparseAxisArray` Tangi. The function `size` is not defined even if it's an `AbstractArray`.
I suppose that `size` is called on each component during a concatenation with Julia 1.9 and it was not the case before.

**Comment by tmigot** [comment]
I tested with julia 1.8 and it works. So, maybe we just wait for the release of 1.9. What do you think?

**Comment by amontoison** [comment]
Yes, let's wait the release of Julia 1.9.

**Comment by tmigot** [comment]
@amontoison Can we close this?

**Comment by amontoison** [comment]
We should open a new PR to see if we still have some errors with Julia nightly.

**Comment by tmigot** [comment]
It was working last week when we made the new release.

**Pull request closed without merging**
